<?php

use Illuminate\Database\Seeder;

class UsertableTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('usertables')->insert([
            'last_name'=>'日置',
            'first_name'=>'慎一',
            'last_name_kana'=>'ヒオキ',
            'first_name_kana'=>'シンイチ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'安藤',
            'first_name'=>'忠雄',
            'last_name_kana'=>'アンドウ',
            'first_name_kana'=>'タダオ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'安藤',
            'first_name'=>'忠雄',
            'last_name_kana'=>'アンドウ',
            'first_name_kana'=>'タダオ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'加藤',
            'first_name'=>'和明',
            'last_name_kana'=>'カトウ',
            'first_name_kana'=>'カズアキ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'加藤',
            'first_name'=>'和明',
            'last_name_kana'=>'カトウ',
            'first_name_kana'=>'カズアキ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'佐藤',
            'first_name'=>'庄司',
            'last_name_kana'=>'サトウ',
            'first_name_kana'=>'ショウジ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'佐藤',
            'first_name'=>'庄司',
            'last_name_kana'=>'サトウ',
            'first_name_kana'=>'ショウジ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'田中',
            'first_name'=>'高明',
            'last_name_kana'=>'タナカ',
            'first_name_kana'=>'タカアキ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'田中',
            'first_name'=>'高明',
            'last_name_kana'=>'タナカ',
            'first_name_kana'=>'タカアキ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'内藤',
            'first_name'=>'俊明',
            'last_name_kana'=>'ナイトウ',
            'first_name_kana'=>'トシアキ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'内藤',
            'first_name'=>'俊明',
            'last_name_kana'=>'ナイトウ',
            'first_name_kana'=>'トシアキ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'浜野谷',
            'first_name'=>'圭吾',
            'last_name_kana'=>'ハマノヤ',
            'first_name_kana'=>'ケイゴ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'浜野谷',
            'first_name'=>'圭吾',
            'last_name_kana'=>'ハマノヤ',
            'first_name_kana'=>'ケイゴ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'松本',
            'first_name'=>'秋絵',
            'last_name_kana'=>'マツモト',
            'first_name_kana'=>'アキエ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'松本',
            'first_name'=>'秋絵',
            'last_name_kana'=>'マツモト',
            'first_name_kana'=>'アキエ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'山本',
            'first_name'=>'大樹',
            'last_name_kana'=>'ヤマモト',
            'first_name_kana'=>'タイキ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'山本',
            'first_name'=>'大樹',
            'last_name_kana'=>'ヤマモト',
            'first_name_kana'=>'タイキ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'楽天',
            'first_name'=>'茉莉',
            'last_name_kana'=>'ラクテン',
            'first_name_kana'=>'マツリ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'楽天',
            'first_name'=>'茉莉',
            'last_name_kana'=>'ラクテン',
            'first_name_kana'=>'マツリ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'渡辺',
            'first_name'=>'善久',
            'last_name_kana'=>'ワタナベ',
            'first_name_kana'=>'ヨシヒサ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'渡辺',
            'first_name'=>'善久',
            'last_name_kana'=>'ワタナベ',
            'first_name_kana'=>'ヨシヒサ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'蒲生',
            'first_name'=>'高尾',
            'last_name_kana'=>'ガモウ',
            'first_name_kana'=>'タカオ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'蒲生',
            'first_name'=>'高尾',
            'last_name_kana'=>'ガモウ',
            'first_name_kana'=>'タカオ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'神宮',
            'first_name'=>'真',
            'last_name_kana'=>'ジングウ',
            'first_name_kana'=>'マコト',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'神宮',
            'first_name'=>'真',
            'last_name_kana'=>'ジングウ',
            'first_name_kana'=>'マコト',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'ントゥシトラ',
            'first_name'=>'マダオ',
            'last_name_kana'=>'ントゥシトラ',
            'first_name_kana'=>'マダオ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'ントゥシトラ',
            'first_name'=>'マダオ',
            'last_name_kana'=>'ントゥシトラ',
            'first_name_kana'=>'マダオ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'ポール',
            'first_name'=>'ショウ',
            'last_name_kana'=>'ポール',
            'first_name_kana'=>'ショウ',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'ポール',
            'first_name'=>'ショウ',
            'last_name_kana'=>'ポール',
            'first_name_kana'=>'ショウ',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'ベン',
            'first_name'=>'ジャック',
            'last_name_kana'=>'ベン',
            'first_name_kana'=>'ジャック',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'ベン',
            'first_name'=>'ジャック',
            'last_name_kana'=>'ベン',
            'first_name_kana'=>'ジャック',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'ゼン',
            'first_name'=>'リーシン',
            'last_name_kana'=>'ゼン',
            'first_name_kana'=>'リーシン',
            'school_id'=>'1',
            'created_at'=>now(),
        ]);
        DB::table('usertables')->insert([
            'last_name'=>'ゼン',
            'first_name'=>'リーシン',
            'last_name_kana'=>'ゼン',
            'first_name_kana'=>'リーシン',
            'school_id'=>'2',
            'created_at'=>now(),
        ]);
    }
}
